/* Generated By:JJTree: Do not edit this line. YoyooClassOrInterfaceName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooClassOrInterfaceName extends SimpleNode {
  public YoyooClassOrInterfaceName(int id) {
    super(id);
  }

  public YoyooClassOrInterfaceName(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7405822d6205b5fb7b9426f2d82c88d7 (do not edit this line) */
