/* Generated By:JJTree&JavaCC: Do not edit this line. YoyooParserConstants.java */
package org.yoyoo.core.engine.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YoyooParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 12;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 13;
  /** RegularExpression Id. */
  int PREPROCESSOR_BLOCK = 14;
  /** RegularExpression Id. */
  int PREPROCESSOR_BLOCK2 = 15;
  /** RegularExpression Id. */
  int PREPROCESSOR_VARIABLE_BLOCK = 16;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 17;
  /** RegularExpression Id. */
  int ABSTRACT = 19;
  /** RegularExpression Id. */
  int BOOLEAN = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int BYTE = 22;
  /** RegularExpression Id. */
  int CASE = 23;
  /** RegularExpression Id. */
  int CATCH = 24;
  /** RegularExpression Id. */
  int CHAR = 25;
  /** RegularExpression Id. */
  int CONST = 26;
  /** RegularExpression Id. */
  int CONTINUE = 27;
  /** RegularExpression Id. */
  int _DEFAULT = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int EXTENDS = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int FINAL = 34;
  /** RegularExpression Id. */
  int FINALLY = 35;
  /** RegularExpression Id. */
  int FLOAT = 36;
  /** RegularExpression Id. */
  int FOR = 37;
  /** RegularExpression Id. */
  int GOTO = 38;
  /** RegularExpression Id. */
  int IF = 39;
  /** RegularExpression Id. */
  int IMPLEMENTS = 40;
  /** RegularExpression Id. */
  int IMPORT = 41;
  /** RegularExpression Id. */
  int INSTANCEOF = 42;
  /** RegularExpression Id. */
  int INT = 43;
  /** RegularExpression Id. */
  int INTERFACE = 44;
  /** RegularExpression Id. */
  int LONG = 45;
  /** RegularExpression Id. */
  int NATIVE = 46;
  /** RegularExpression Id. */
  int NEW = 47;
  /** RegularExpression Id. */
  int NULL = 48;
  /** RegularExpression Id. */
  int PACKAGE = 49;
  /** RegularExpression Id. */
  int PRIVATE = 50;
  /** RegularExpression Id. */
  int PROTECTED = 51;
  /** RegularExpression Id. */
  int PUBLIC = 52;
  /** RegularExpression Id. */
  int RETURN = 53;
  /** RegularExpression Id. */
  int SHORT = 54;
  /** RegularExpression Id. */
  int STATIC = 55;
  /** RegularExpression Id. */
  int SUPER = 56;
  /** RegularExpression Id. */
  int SWITCH = 57;
  /** RegularExpression Id. */
  int THIS = 58;
  /** RegularExpression Id. */
  int THROW = 59;
  /** RegularExpression Id. */
  int THROWS = 60;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 61;
  /** RegularExpression Id. */
  int TRUE = 62;
  /** RegularExpression Id. */
  int TRY = 63;
  /** RegularExpression Id. */
  int VOID = 64;
  /** RegularExpression Id. */
  int WHILE = 65;
  /** RegularExpression Id. */
  int STRING = 66;
  /** RegularExpression Id. */
  int YOYOOEXPR = 67;
  /** RegularExpression Id. */
  int YOYOOREF = 68;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 69;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 70;
  /** RegularExpression Id. */
  int HEX_LITERAL = 71;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 72;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 73;
  /** RegularExpression Id. */
  int EXPONENT = 74;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 75;
  /** RegularExpression Id. */
  int STRING_LITERAL = 76;
  /** RegularExpression Id. */
  int MULTILINE_STRING_LITERAL = 77;
  /** RegularExpression Id. */
  int LPAREN = 78;
  /** RegularExpression Id. */
  int RPAREN = 79;
  /** RegularExpression Id. */
  int LBRACE = 80;
  /** RegularExpression Id. */
  int RBRACE = 81;
  /** RegularExpression Id. */
  int LBRACKET = 82;
  /** RegularExpression Id. */
  int RBRACKET = 83;
  /** RegularExpression Id. */
  int SEMICOLON = 84;
  /** RegularExpression Id. */
  int COMMA = 85;
  /** RegularExpression Id. */
  int DOT = 86;
  /** RegularExpression Id. */
  int ASSIGN = 87;
  /** RegularExpression Id. */
  int GT = 88;
  /** RegularExpression Id. */
  int LT = 89;
  /** RegularExpression Id. */
  int BANG = 90;
  /** RegularExpression Id. */
  int HOOK = 91;
  /** RegularExpression Id. */
  int COLON = 92;
  /** RegularExpression Id. */
  int EQ = 93;
  /** RegularExpression Id. */
  int LE = 94;
  /** RegularExpression Id. */
  int GE = 95;
  /** RegularExpression Id. */
  int NE = 96;
  /** RegularExpression Id. */
  int SC_OR = 97;
  /** RegularExpression Id. */
  int SC_AND = 98;
  /** RegularExpression Id. */
  int INCR = 99;
  /** RegularExpression Id. */
  int DECR = 100;
  /** RegularExpression Id. */
  int PLUS = 101;
  /** RegularExpression Id. */
  int MINUS = 102;
  /** RegularExpression Id. */
  int STAR = 103;
  /** RegularExpression Id. */
  int SLASH = 104;
  /** RegularExpression Id. */
  int REM = 105;
  /** RegularExpression Id. */
  int PLUSASSIGN = 106;
  /** RegularExpression Id. */
  int MINUSASSIGN = 107;
  /** RegularExpression Id. */
  int STARASSIGN = 108;
  /** RegularExpression Id. */
  int SLASHASSIGN = 109;
  /** RegularExpression Id. */
  int SPECIALEXPRSTART = 110;
  /** RegularExpression Id. */
  int SPECIALEXPREND = 111;
  /** RegularExpression Id. */
  int IDENTIFIER = 112;
  /** RegularExpression Id. */
  int LETTER = 113;
  /** RegularExpression Id. */
  int PART_LETTER = 114;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_PREPROCESSOR_BLOCK = 3;
  /** Lexical state. */
  int IN_PREPROCESSOR_BLOCK2 = 4;
  /** Lexical state. */
  int IN_PREPROCESSOR_VARIABLE_BLOCK = 5;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"#*/\"",
    "\"//~#*/\"",
    "\"?*/\"",
    "\"*/\"",
    "<token of kind 18>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"synchronized\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\"string\"",
    "\"expr\"",
    "\"ref\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<MULTILINE_STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"/*<\"",
    "\">*/\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"&\"",
    "\"%=\"",
    "\"~\"",
  };

}
