/* Generated By:JJTree: Do not edit this line. YoyooStmExprAssignExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooStmExprAssignExpr extends SimpleNode {
  public YoyooStmExprAssignExpr(int id) {
    super(id);
  }

  public YoyooStmExprAssignExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ea7424e81caf17be3a96be02c52d0e3 (do not edit this line) */
