/* Generated By:JJTree: Do not edit this line. YoyooLiteralBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooLiteralBoolean extends SimpleNode {
  public YoyooLiteralBoolean(int id) {
    super(id);
  }

  public YoyooLiteralBoolean(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a7e51db9f040edcfcbecba30e73fb275 (do not edit this line) */
