/* Generated By:JJTree: Do not edit this line. YoyooWildcardBoundsType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooWildcardBoundsType extends SimpleNode {
  public YoyooWildcardBoundsType(int id) {
    super(id);
  }

  public YoyooWildcardBoundsType(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb7e8c4ea1251fd0b97f5e080d9608dc (do not edit this line) */
