/* Generated By:JJTree: Do not edit this line. YoyooPrefixOpt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooPrefixOpt extends SimpleNode {
  public YoyooPrefixOpt(int id) {
    super(id);
  }

  public YoyooPrefixOpt(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d87fef8c220b108dec25ea67a7a8dff9 (do not edit this line) */
