/* Generated By:JJTree: Do not edit this line. YoyooAlloPrimitiveExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooAlloPrimitiveExpr extends SimpleNode {
  public YoyooAlloPrimitiveExpr(int id) {
    super(id);
  }

  public YoyooAlloPrimitiveExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=da512c5fb67d60e42a74f72aa90b393d (do not edit this line) */
