/* Generated By:JJTree: Do not edit this line. YoyooPostfixOpt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooPostfixOpt extends SimpleNode {
  public YoyooPostfixOpt(int id) {
    super(id);
  }

  public YoyooPostfixOpt(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0708d9b496ca60b451f9386f8d4ae80 (do not edit this line) */
