/* Generated By:JJTree: Do not edit this line. YoyooPrimitiveTypeName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooPrimitiveTypeName extends SimpleNode {
  public YoyooPrimitiveTypeName(int id) {
    super(id);
  }

  public YoyooPrimitiveTypeName(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1b9e819e4bf02bbb1ee0d3b895b708a5 (do not edit this line) */
