/* Generated By:JavaCC: Do not edit this line. YoyooParserTreeConstants.java Version 5.0 */
package org.yoyoo.core.engine.parser;

public interface YoyooParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECL = 1;
  public int JJTIMPORTDECL = 2;
  public int JJTTYPEDECL = 3;
  public int JJTABSTRACT = 4;
  public int JJTTYPEDECLNAME = 5;
  public int JJTMODIFIER = 6;
  public int JJTVOID = 7;
  public int JJTDECLARATIONNAME = 8;
  public int JJTEXTENDSLIST = 9;
  public int JJTEXTENDSNAME = 10;
  public int JJTIMPLEMENTSLIST = 11;
  public int JJTIMPLEMENTSNAME = 12;
  public int JJTSTATIC = 13;
  public int JJTCONSTRUCTOR = 14;
  public int JJTCONSTRUCTORNAME = 15;
  public int JJTCONSTRUCTORBODY = 16;
  public int JJTEXPLICITCONSTRUCTOR = 17;
  public int JJTTHISEXPLICITCONSTRUCTOR = 18;
  public int JJTARGUMENTS = 19;
  public int JJTSUPEREXPLICITCONSTRUCTOR = 20;
  public int JJTMEDTHODDECL = 21;
  public int JJTMEDTHODDECLBODY = 22;
  public int JJTMETHODNAME = 23;
  public int JJTFIELDDECL = 24;
  public int JJTFINAL = 25;
  public int JJTVARIABLEDECLARATORID = 26;
  public int JJTVARIABLEINITIALIZER = 27;
  public int JJTARRAYINIT = 28;
  public int JJTFORMALPARAMETERS = 29;
  public int JJTFORMALPARAMETER = 30;
  public int JJTFORMALPARAMETERTYPE = 31;
  public int JJTFORMALPARAMETERNAME = 32;
  public int JJTPRIMITIVETYPE = 33;
  public int JJTPRIMITIVETYPENAME = 34;
  public int JJTARRAYDECL = 35;
  public int JJTREFERENCETYPE = 36;
  public int JJTCLASSORINTERFACENAME = 37;
  public int JJTCLASSORINTERFACETYPEARGUMENTS = 38;
  public int JJTRESULTTYPE = 39;
  public int JJTVOIDTYPE = 40;
  public int JJTTYPEARGUMENT = 41;
  public int JJTTYPEARGUMENTTYPE = 42;
  public int JJTWILDCARDBOUNDS = 43;
  public int JJTWILDCARDBOUNDSEXTENDS = 44;
  public int JJTWILDCARDBOUNDSTYPE = 45;
  public int JJTWILDCARDBOUNDSSUPER = 46;
  public int JJTTYPEPARAMETERS = 47;
  public int JJTTYPEPARAMETER = 48;
  public int JJTTYPEPARAMETERNAME = 49;
  public int JJTTYPEBOUNDNAME = 50;
  public int JJTTHROWSNAMELIST = 51;
  public int JJTTHROWNAME = 52;
  public int JJTASSIGNVAL = 53;
  public int JJTASSIGNEXPR = 54;
  public int JJTASSIGNMENTOPERATOR = 55;
  public int JJTCONDTRUEEXPR = 56;
  public int JJTCONDFALSEEXPR = 57;
  public int JJTCONDEXPR = 58;
  public int JJTOPT = 59;
  public int JJTBIONEXPR = 60;
  public int JJTPREFIXOPT = 61;
  public int JJTPOSTFIXOPT = 62;
  public int JJTPOSTFIXEXPR = 63;
  public int JJTCASTEXPRESSION = 64;
  public int JJTCASTTYPE = 65;
  public int JJTCASTEXPR = 66;
  public int JJTPRIMARYEXPR = 67;
  public int JJTTHIS = 68;
  public int JJTSUPERREFID = 69;
  public int JJTBRACKETEXPR = 70;
  public int JJTALLOEXPR = 71;
  public int JJTNAMEEXPR = 72;
  public int JJTARRAYINDEXEXPR = 73;
  public int JJTREFID = 74;
  public int JJTLITERALINTEGER = 75;
  public int JJTLITERALFLOAT = 76;
  public int JJTLITERALCHAR = 77;
  public int JJTLITERALSTRING = 78;
  public int JJTLITERALBOOLEAN = 79;
  public int JJTLITERALNULL = 80;
  public int JJTSPECIALEXPRTYPE = 81;
  public int JJTSPECIALEXPRTYPENAME = 82;
  public int JJTSPECIALEXPR = 83;
  public int JJTSPECIALEXPRBODY = 84;
  public int JJTREF = 85;
  public int JJTREFVALUETYPE = 86;
  public int JJTARGUMENT = 87;
  public int JJTALLOPRIMITIVEEXPR = 88;
  public int JJTALLOCATIONNAME = 89;
  public int JJTALLOREFERENCEEXPR = 90;
  public int JJTARRAYDIMSANDINITS = 91;
  public int JJTARRAYDIMSEXPR = 92;
  public int JJTARRAYDIMS = 93;
  public int JJTLABELEDSTATEMENT = 94;
  public int JJTLABELEDSTMLABEL = 95;
  public int JJTLABELEDSTMBODY = 96;
  public int JJTBLOCK = 97;
  public int JJTBLOCKSTATEMENTBODYSTM = 98;
  public int JJTLOCALVARIABLEDECLARATION = 99;
  public int JJTEMPTYSTATEMENT = 100;
  public int JJTSTATEMENTEXPRESSION = 101;
  public int JJTSTMEXPRPOSTOPT = 102;
  public int JJTSTMEXPRASSIGNEXPR = 103;
  public int JJTSWITCHSTATEMENT = 104;
  public int JJTSWITCHKEY = 105;
  public int JJTSWITCHCASE = 106;
  public int JJTCASEBLOCKSTM = 107;
  public int JJTCASESTM = 108;
  public int JJTSWITCHDEFAULT = 109;
  public int JJTCASEEXPR = 110;
  public int JJTIFSTATEMENT = 111;
  public int JJTIFCONDEXPR = 112;
  public int JJTIFSTM = 113;
  public int JJTELSESTM = 114;
  public int JJTWHILESTATEMENT = 115;
  public int JJTWHILECOND = 116;
  public int JJTLOOPSTM = 117;
  public int JJTDOSTATEMENT = 118;
  public int JJTDOCOND = 119;
  public int JJTFORSTATEMENT = 120;
  public int JJTFORCOND = 121;
  public int JJTFORINIT = 122;
  public int JJTFORUPDATE = 123;
  public int JJTBREAKSTATEMENT = 124;
  public int JJTBREAKLABEL = 125;
  public int JJTCONTINUESTATEMENT = 126;
  public int JJTCONTINUELABEL = 127;
  public int JJTRETURNSTATEMENT = 128;
  public int JJTRETURNEXPR = 129;
  public int JJTTHROWSTATEMENT = 130;
  public int JJTTHROWEXPR = 131;
  public int JJTSYNCHRONIZEDSTATEMENT = 132;
  public int JJTSYNEXPR = 133;
  public int JJTSYNBLOCK = 134;
  public int JJTTRYSTATEMENT = 135;
  public int JJTTRYBLOCK = 136;
  public int JJTCATCHBLOCK = 137;
  public int JJTFINALLYBLOCK = 138;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDecl",
    "ImportDecl",
    "TypeDecl",
    "Abstract",
    "TypeDeclName",
    "Modifier",
    "void",
    "DeclarationName",
    "ExtendsList",
    "ExtendsName",
    "ImplementsList",
    "ImplementsName",
    "Static",
    "Constructor",
    "ConstructorName",
    "ConstructorBody",
    "ExplicitConstructor",
    "ThisExplicitConstructor",
    "Arguments",
    "SuperExplicitConstructor",
    "MedthodDecl",
    "MedthodDeclBody",
    "MethodName",
    "FieldDecl",
    "Final",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInit",
    "FormalParameters",
    "FormalParameter",
    "FormalParameterType",
    "FormalParameterName",
    "PrimitiveType",
    "PrimitiveTypeName",
    "ArrayDecl",
    "ReferenceType",
    "ClassOrInterfaceName",
    "ClassOrInterfaceTypeArguments",
    "ResultType",
    "VoidType",
    "TypeArgument",
    "TypeArgumentType",
    "WildcardBounds",
    "WildcardBoundsExtends",
    "WildcardBoundsType",
    "WildcardBoundsSuper",
    "TypeParameters",
    "TypeParameter",
    "TypeParameterName",
    "TypeBoundName",
    "ThrowsNameList",
    "ThrowName",
    "AssignVal",
    "AssignExpr",
    "AssignmentOperator",
    "CondTrueExpr",
    "CondFalseExpr",
    "CondExpr",
    "Opt",
    "BionExpr",
    "PrefixOpt",
    "PostfixOpt",
    "PostfixExpr",
    "CastExpression",
    "CastType",
    "CastExpr",
    "PrimaryExpr",
    "This",
    "SuperRefId",
    "BracketExpr",
    "AlloExpr",
    "NameExpr",
    "ArrayIndexExpr",
    "RefId",
    "LiteralInteger",
    "LiteralFloat",
    "LiteralChar",
    "LiteralString",
    "LiteralBoolean",
    "LiteralNull",
    "SpecialExprType",
    "SpecialExprTypeName",
    "SpecialExpr",
    "SpecialExprBody",
    "Ref",
    "RefValueType",
    "Argument",
    "AlloPrimitiveExpr",
    "AllocationName",
    "AlloReferenceExpr",
    "ArrayDimsAndInits",
    "ArrayDimsExpr",
    "ArrayDims",
    "LabeledStatement",
    "LabeledStmLabel",
    "LabeledStmBody",
    "Block",
    "BlockStatementBodyStm",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "StmExprPostOpt",
    "StmExprAssignExpr",
    "SwitchStatement",
    "SwitchKey",
    "SwitchCase",
    "CaseBlockStm",
    "CaseStm",
    "SwitchDefault",
    "CaseExpr",
    "IfStatement",
    "IfCondExpr",
    "IfStm",
    "ElseStm",
    "WhileStatement",
    "WhileCond",
    "LoopStm",
    "DoStatement",
    "DoCond",
    "ForStatement",
    "ForCond",
    "ForInit",
    "ForUpdate",
    "BreakStatement",
    "BreakLabel",
    "ContinueStatement",
    "ContinueLabel",
    "ReturnStatement",
    "ReturnExpr",
    "ThrowStatement",
    "ThrowExpr",
    "SynchronizedStatement",
    "SynExpr",
    "SynBlock",
    "TryStatement",
    "TryBlock",
    "CatchBlock",
    "FinallyBlock",
  };
}
/* JavaCC - OriginalChecksum=86eba40a75fc75ba29bf3d7f0af2a654 (do not edit this line) */
