/* Generated By:JJTree: Do not edit this line. YoyooPostfixPrimaryExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY= */
package org.yoyoo.core.engine.parser;

public class YoyooPostfixPrimaryExpr extends SimpleNode {
  public YoyooPostfixPrimaryExpr(int id) {
    super(id);
  }

  public YoyooPostfixPrimaryExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14e3d838b9743ca4a27f28b78fcd9577 (do not edit this line) */
