/* Generated By:JJTree: Do not edit this line. YoyooVariableDeclaratorId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooVariableDeclaratorId extends SimpleNode {
  public YoyooVariableDeclaratorId(int id) {
    super(id);
  }

  public YoyooVariableDeclaratorId(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1d3c7f9ec46138a03a0e84ad7153883 (do not edit this line) */
