/* Generated By:JJTree: Do not edit this line. YoyooFormalParameterName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooFormalParameterName extends SimpleNode {
  public YoyooFormalParameterName(int id) {
    super(id);
  }

  public YoyooFormalParameterName(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ce81df93ad1a0f38220425c096fec058 (do not edit this line) */
