/* Generated By:JJTree: Do not edit this line. YoyooBlockStatementBodyStm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooBlockStatementBodyStm extends SimpleNode {
  public YoyooBlockStatementBodyStm(int id) {
    super(id);
  }

  public YoyooBlockStatementBodyStm(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=30762152a49289314631712ced9f92a2 (do not edit this line) */
