/* Generated By:JJTree: Do not edit this line. YoyooFormalParameterType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooFormalParameterType extends SimpleNode {
  public YoyooFormalParameterType(int id) {
    super(id);
  }

  public YoyooFormalParameterType(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2239817978d6c1e6b18ff5a73e4af116 (do not edit this line) */
