/* Generated By:JJTree: Do not edit this line. YoyooStmExprPostOpt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooStmExprPostOpt extends SimpleNode {
  public YoyooStmExprPostOpt(int id) {
    super(id);
  }

  public YoyooStmExprPostOpt(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5594fa0f92eba00b00418c4615992a4 (do not edit this line) */
