/* Generated By:JJTree: Do not edit this line. YoyooArrayDimsAndInits.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooArrayDimsAndInits extends SimpleNode {
  public YoyooArrayDimsAndInits(int id) {
    super(id);
  }

  public YoyooArrayDimsAndInits(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2650280408704bc520fb6e1f6d28345a (do not edit this line) */
