/* Generated By:JJTree: Do not edit this line. YoyooSuperRefId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooSuperRefId extends SimpleNode {
  public YoyooSuperRefId(int id) {
    super(id);
  }

  public YoyooSuperRefId(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=435899229fa3580ef5f05425c54d35b5 (do not edit this line) */
