/* Generated By:JJTree: Do not edit this line. YoyooTypeArgumentType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooTypeArgumentType extends SimpleNode {
  public YoyooTypeArgumentType(int id) {
    super(id);
  }

  public YoyooTypeArgumentType(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9a1b79100486c96a8c58b4e8578246b5 (do not edit this line) */
