/* Generated By:JJTree: Do not edit this line. YoyooLabeledStmLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooLabeledStmLabel extends SimpleNode {
  public YoyooLabeledStmLabel(int id) {
    super(id);
  }

  public YoyooLabeledStmLabel(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9008285864c9c46663863c3d97111981 (do not edit this line) */
