/* Generated By:JJTree: Do not edit this line. YoyooWildcardBoundsExtends.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooWildcardBoundsExtends extends SimpleNode {
  public YoyooWildcardBoundsExtends(int id) {
    super(id);
  }

  public YoyooWildcardBoundsExtends(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=19c1404078ccfed19f01e00972f73745 (do not edit this line) */
