/* Generated By:JJTree: Do not edit this line. YoyooWildcardBoundsSuper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooWildcardBoundsSuper extends SimpleNode {
  public YoyooWildcardBoundsSuper(int id) {
    super(id);
  }

  public YoyooWildcardBoundsSuper(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7800c0a9cf60fdbef4d17a245a5b83c8 (do not edit this line) */
