/* Generated By:JJTree: Do not edit this line. YoyooMedthodDeclBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooMedthodDeclBody extends SimpleNode {
  public YoyooMedthodDeclBody(int id) {
    super(id);
  }

  public YoyooMedthodDeclBody(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b6900b7c494e8e087d4aa44123a1adf2 (do not edit this line) */
