/* Generated By:JJTree: Do not edit this line. YoyooLiteralNull.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooLiteralNull extends SimpleNode {
  public YoyooLiteralNull(int id) {
    super(id);
  }

  public YoyooLiteralNull(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1528ddb57abeb67497659945122ef37 (do not edit this line) */
