/* Generated By:JJTree: Do not edit this line. YoyooCondFalseExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooCondFalseExpr extends SimpleNode {
  public YoyooCondFalseExpr(int id) {
    super(id);
  }

  public YoyooCondFalseExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b28f5075f5476664a7a9a3682c4bb1da (do not edit this line) */
