/* Generated By:JJTree: Do not edit this line. YoyooSpecialExprBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooSpecialExprBody extends SimpleNode {
  public YoyooSpecialExprBody(int id) {
    super(id);
  }

  public YoyooSpecialExprBody(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=caf0e72d551ca3b27f9299cda6648c8c (do not edit this line) */
