/* Generated By:JJTree: Do not edit this line. YoyooThisExplicitConstructor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooThisExplicitConstructor extends SimpleNode {
  public YoyooThisExplicitConstructor(int id) {
    super(id);
  }

  public YoyooThisExplicitConstructor(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=778e04749395fe908d58d0d65a8ff3c1 (do not edit this line) */
