/* Generated By:JJTree: Do not edit this line. YoyooPostfixExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooPostfixExpr extends SimpleNode {
  public YoyooPostfixExpr(int id) {
    super(id);
  }

  public YoyooPostfixExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4de3b0e182c46d1bc0144da7c0a4d696 (do not edit this line) */
