/* Generated By:JJTree: Do not edit this line. YoyooTypeBoundName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooTypeBoundName extends SimpleNode {
  public YoyooTypeBoundName(int id) {
    super(id);
  }

  public YoyooTypeBoundName(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=68d12222e55ad1eb0c3e51e3d9921668 (do not edit this line) */
