/* Generated By:JJTree: Do not edit this line. YoyooArrayIndexExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooArrayIndexExpr extends SimpleNode {
  public YoyooArrayIndexExpr(int id) {
    super(id);
  }

  public YoyooArrayIndexExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c6383664aa97d425bcf2e74c23dd861 (do not edit this line) */
