/* Generated By:JJTree: Do not edit this line. YoyooLabeledStmBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooLabeledStmBody extends SimpleNode {
  public YoyooLabeledStmBody(int id) {
    super(id);
  }

  public YoyooLabeledStmBody(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a24b41e8e6713314deae22c123e65191 (do not edit this line) */
