/* Generated By:JJTree: Do not edit this line. YoyooCondTrueExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooCondTrueExpr extends SimpleNode {
  public YoyooCondTrueExpr(int id) {
    super(id);
  }

  public YoyooCondTrueExpr(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d9787a2bfa68907d3495c3d1c1088258 (do not edit this line) */
