/* Generated By:JJTree: Do not edit this line. YoyooClassOrInterfaceTypeArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooClassOrInterfaceTypeArguments extends SimpleNode {
  public YoyooClassOrInterfaceTypeArguments(int id) {
    super(id);
  }

  public YoyooClassOrInterfaceTypeArguments(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=160570121f56ea354cb5071cd3d4252a (do not edit this line) */
