/* Generated By:JJTree: Do not edit this line. YoyooSpecialExprTypeName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Yoyoo,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.yoyoo.core.engine.parser;

public
class YoyooSpecialExprTypeName extends SimpleNode {
  public YoyooSpecialExprTypeName(int id) {
    super(id);
  }

  public YoyooSpecialExprTypeName(YoyooParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YoyooParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95bf37eb70ccb1ed13af109833df569d (do not edit this line) */
